### ISSUE TITLE
[Bug] pycharm 경로 import 문제 발생

### ISSUE THREAD

**Issue by dasd412** [SWM14-Architect/moview-core-service#13]
![스크린샷 2023-07-11 오전 9 52 13](https://github.com/SWM14-Architect/moview-core-service/assets/45190017/3a41cf9e-653f-4abe-9a6b-39d88abba19c)

맨 위 import 문을 보시면, 경로 문제가 발생합니다. 
본인 개발 환경에선 어떻게 해결하셨는 지, 이 이슈에 공유해주시면 감사하겠습니다.
그리고 이 이슈는 pinned되어야 할 것 같아요.

**Comment by westreed** [comment]
moview 폴더를 우클릭해서 소스폴더로 전환해주시면 됩니다. 모바일이라 여기까지만 쓰고, 나중에 업뎃 ㅎ

**Comment by dasd412** [comment]
해결하긴 했습니다. 
![스크린샷 2023-07-11 오전 10 54 52](https://github.com/SWM14-Architect/moview-core-service/assets/45190017/d7a15948-4684-430c-8e42-332bd8561083)

근데 또 다른 문제가 있네요

**Comment by dasd412** [comment]
![스크린샷 2023-07-11 오전 10 57 22](https://github.com/SWM14-Architect/moview-core-service/assets/45190017/dd2e432e-f659-44b2-b863-1d5d3c32d23c)

이건 뭐죠?

**Comment by westreed** [comment]
Flask에서 로깅처리를 할때 logging 폴더를 사용하는 듯 합니다. logging 폴더의 이름을 임시로 바꿔주시면 해결됩니다.


그리고 실행은 app.py에서 해야 합니다.

**Comment by dasd412** [comment]
해결 완료입니다. 이 이슈는 pinned 하겠습니다.
