### ISSUE TITLE
LLM Token 제한이 해결되기 전까진 서버 이중화가 아무 의미 없으므로, 서버 이중화는 보류

### ISSUE THREAD

**Issue by dasd412** [SWM14-Architect/moview-core-service#130]
서버 이중화, DB 이중화를 하더라도 핵심인 LLM Token에서 1분 제한이 걸려버리면 아무 소용 없다.(LLM이 병목이다.)
해당 문제가 해결 되고나서 인프라를 다루자.

**Comment by dasd412** [comment]
langchain 이었을 때 한번에 비동기 콜 200개였는데, openai로 바꾸니까 한 번에 비동기 콜 500개 *2 해도 거뜬하다.
즉 1분당 토큰 제한은 크게 신경쓸 필요 없어졌다. 이제 인프라 다뤄도 될 듯

**Comment by westreed** [comment]
1분당 토큰 제한이랑 다른 개념이라고 보입니다.
토큰제한은 말그대로 토큰수의 제한이고, 분당 요청 제한은 3.5 터보, 3.5터보-16k 둘다 5000이에요.
5001번 호출하면 제한에 걸릴 겁니다.
