### ISSUE TITLE
test/analyzer 내 테스트 코드 수정 요청

### ISSUE THREAD

**Issue by dasd412** [SWM14-Architect/moview-core-service#35]
DataManager 삭제 후, 테스트 코드에서 오류가 발생합니다. 리팩토링 부탁합니다.

**Comment by westreed** [comment]
Controller는 전부 새롭게 만들어질 예정이고, 모듈 또한 거의 새롭게 제작될 예정이라 테스트 코드는 그대로 두었습니다.
모듈에서 [follow_up_question_generator.py](https://github.com/SWM14-Architect/moview-core-service/blob/main/moview/modules/question_generator/follow_up_question_generator.py)과 [init_question_generator.py](https://github.com/SWM14-Architect/moview-core-service/blob/main/moview/modules/question_generator/init_question_generator.py)은 그대로 남아있어서 이 2개의 모듈은 테스트 코드를 리팩토링 하겠습니다!
