### ISSUE TITLE
스레드 안전하지 않은 코드 수정 필요

### ISSUE THREAD

**Issue by dasd412** [SWM14-Architect/moview-core-service#63]
다음 코드는 스레드 안전하지 않은 코드이다.

```
class InterviewQuestions(BaseModel):
    """
    인터뷰 초기 질문과 꼬리질문을 관리하는 클래스입니다.
    """
    initial_question_list: List = []  # 초기 질문 리스트
    followup_question_list = []  # 꼬리 질문 리스트
    initial_question_index: int = 0  # 초기 질문 인덱스 i
    followup_question_count: int = 0  # i 번째 초기 질문에서 출제한 꼬리질문 횟수
    MAX_FOLLOWUP_QUESTION_COUNT: int = 3  # 꼬리질문 최대 횟수

    def get_next_initial_question(self):
        if self.initial_question_index >= len(self.initial_question_list):
            raise StopIteration("초기 질문을 모두 사용하였습니다.")

        self.initial_question_index += 1

        # 꼬리질문 초기화
        self.followup_question_count = 0

        if not self.is_initial_questions_end():
            return self.initial_question_list[self.initial_question_index]
        else:
            return []

    def save_followup_question(self, followup_question: str):
        self.followup_question_count += 1
        self.followup_question_list.append(followup_question)

    def is_initial_questions_end(self) -> bool:
        return self.initial_question_index >= len(self.initial_question_list) - 1

    def is_followup_questions_end(self) -> bool:
        return self.followup_question_count >= self.MAX_FOLLOWUP_QUESTION_COUNT
```

## 분석 결과

제시된 파이썬 코드는 스레드 안전(thread-safe)하지 않습니다. 클래스의 여러 메서드에서 내부 상태를 변경하는 연산을 수행하고 있으며, 동시에 여러 스레드가 이러한 메서드를 호출할 경우 데이터 경쟁(race condition)이 발생할 수 있습니다.

예를 들면:

get_next_initial_question 메서드에서 self.initial_question_index를 증가시키고, 다른 스레드가 동시에 이 메서드를 호출하면 self.initial_question_index 값이 예상보다 더 빨리 증가할 수 있습니다.
save_followup_question 메서드에서 self.followup_question_count를 증가시키고 self.followup_question_list에 추가하는 작업을 동시에 여러 스레드가 호출하면 꼬리질문 리스트에 여러 개의 질문이 중복으로 추가될 수 있습니다.

**Comment by dasd412** [comment]
mongodb document 등 여러 부분에서 이러한 문제들이 많이 있다.
document의 경우에는 데이터 구조를 바꿈으로써 해결할 수 있다.

(Ex)
1. 위 코드의 index 대신, 유일한 id 값으로 대체하여 document들을 관리한다.
2. 다큐먼트 스레드 안전을 몽고 db에게 맡겨버린다.

**Comment by dasd412** [comment]
## 질문
몽고 db에서 특정 _id 값을 갖는 document를 접근할 때, db 자체에서 Locking이 걸리나요?

## 답변

MongoDB는 MMAPv1 스토리지 엔진을 사용할 때 데이터베이스 수준의 락을 제공했습니다. 그러나 MongoDB 3.0 이후로 기본 스토리지 엔진으로 사용되는 WiredTiger에서는 더 세밀한 다큐먼트 수준의 락킹(concurrency control)을 제공합니다.

WiredTiger 스토리지 엔진에서:

락은 다큐먼트 수준에서 발생합니다. 이는 여러 클라이언트가 동시에 다른 다큐먼트를 수정할 수 있음을 의미합니다.
특정 다큐먼트에 대한 쓰기 작업이 발생하면 해당 다큐먼트에 락이 걸립니다. 다른 클라이언트는 동일한 다큐먼트를 수정할 수 없습니다.
읽기 작업은 다른 읽기 작업과 겹칠 수 있으나, 쓰기 작업과 동시에 발생할 경우 락이 걸리게 됩니다. 이는 기본적으로 WiredTiger의 "snapshot isolation"에서 동작하는 방식입니다.
요약하면, WiredTiger 스토리지 엔진을 사용하는 MongoDB에서 특정 _id 값을 갖는 문서를 쓰기 작업으로 접근할 때 해당 문서에 락이 걸립니다. 동시에 해당 문서를 수정하려는 다른 작업은 대기 상태가 됩니다.

**Comment by ssfic3380** [comment]
```
class InterviewAnswerEvaluationService:
    def __init__(self):
        self.repository = IntervieweeDataRepository(mongo_config=MongoConfig())

        self.scorer = AnswerScorer()
        self.analyzer = AnswerAnalyzer()

    def evaluate_answers_of_interviewee(self, session_id):

        found_interview_data = self.repository.find_by_session_id(session_id=session_id)

        if found_interview_data is None:
            raise Exception("Interview history not found.")

        question_list = found_interview_data.interviewee_answer_evaluations.question_list
        answer_list = found_interview_data.interviewee_answer_evaluations.answer_list
        category_and_sub_category_list = found_interview_data.interviewee_answer_evaluations.category_and_sub_category_list
```

유저의 면접 답변을 평가하는 서비스인데, 서비스가 thread-safe 하지 않아서 다른 요청이 들어오게 되면 found_interview_data의 값이 덮어 씌워질 위험이 있는 것 같습니다.

**Comment by dasd412** [comment]
v2에서 백엔드 엔티티 개선됨.
