### ISSUE TITLE
비슷한 내용의 초기질문이 계속 출제됨

### ISSUE THREAD

**Issue by westreed** [SWM14-Architect/moview-core-service#75]
초기질문 프롬프트에 비슷한 질문을 제외해달라는 내용 추가하기.

**Comment by dasd412** [comment]
초기 질문 a와 초기 질문 b가 비슷한 내용인 경우 -> 중복 제거를 위해 초기 질문 끼리의 컨텍스트 또는 메모리가 필요함.

**Comment by dasd412** [comment]
Langchain의 summary memory 같은 걸로 구현하는게 어떤지
